### ISSUE TITLE
Cant compile after installing Phx2Ban

### ISSUE THREAD

**Issue by jaeyson** [ezsuite/community#2]
Hi Peter and Alex,

I followed the instructions and I can verify that the library is installed and can see it in /deps directory. Here's what I'm seeing:

```bash
$ mix compile
==> phx_2_ban
Compiling 17 files (.ex)
     error: undefined function send_data_to_chart/2 (expected Phx2Ban.LiveDashboardPlugin to define such a function or for it to be imported, but none are available)
     │
 249 │       send_data_to_chart(unique_ip_stats_chart_id(), unique_ip_data)
     │       ^^^^^^^^^^^^^^^^^^
     │
     └─ lib/phx_2_ban/live_dashboard.ex:249:7: Phx2Ban.LiveDashboardPlugin.update_charts/1

     error: undefined function send_data_to_chart/2 (expected Phx2Ban.LiveDashboardPlugin to define such a function or for it to be imported, but none are available)
     │
 248 │       send_data_to_chart(request_stats_chart_id(), request_data)
     │       ^^^^^^^^^^^^^^^^^^
     │
     └─ lib/phx_2_ban/live_dashboard.ex:248:7: Phx2Ban.LiveDashboardPlugin.update_charts/1

    error: undefined function live_table/1 (expected Phx2Ban.LiveDashboardPlugin to define such a function or for it to be imported, but none are available)
    │
 42 │       ~H"""
    │       ^^^^^
    │
    └─ lib/phx_2_ban/live_dashboard.ex:42: Phx2Ban.LiveDashboardPlugin.render/1

    error: undefined function live_chart/1 (expected Phx2Ban.LiveDashboardPlugin to define such a function or for it to be imported, but none are available)
    │
 42 │       ~H"""
    │       ^^^^^
    │
    └─ lib/phx_2_ban/live_dashboard.ex:42: Phx2Ban.LiveDashboardPlugin.render/1


== Compilation error in file lib/phx_2_ban/live_dashboard.ex ==
** (CompileError) lib/phx_2_ban/live_dashboard.ex: cannot compile module Phx2Ban.LiveDashboardPlugin (errors have been logged)

could not compile dependency :phx_2_ban, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phx_2_ban --force", update it with "mix deps.update phx_2_ban" or clean it with "mix deps.clean phx_2_ban"
```

I removed `deps` and `_build` directories before running `mix deps.get`, still the same problem. Neither `mix deps.compile phx_2_ban --force` nor clean and updating it worked.

Host env:
- Macos M1 14.2.1 (23C71)
- Elixir v1.17.0, OTP 27.0
- Phoenix 1.6.16
- phoenix_live_dashboard 0.7.2
- remote_ip 1.2.0
- telemetry_metrics 1.0

**Comment by PJUllrich** [comment]
Hey, it seems that the phoenix_live_dashboard imports the missing functions above only from version `0.8.0` onwards. Could you update `phoenix_live_dashboard` to `0.8.0` or above (latest is `0.8.5`) and try again, please? If this works, I'll bump our required version in Phx2Ban.

**Comment by jaeyson** [comment]
Thanks @PJUllrich. On CI (Github Actions) when testing, here's what I saw:

```bash
** (Mix) Could not start application Sample: Sample.Application.start(:normal, []) returned an error: shutdown: failed to start child: Phx2Ban
    ** (EXIT) shutdown: failed to start child: Phx2Ban.Metrics
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function DateTime.shift/2 is undefined or private
                (elixir 1.15.8) DateTime.shift(~U[2024-11-28 14:00:00Z], [hour: 0])
                (phx_2_ban 0.2.0) lib/phx_2_ban/metrics.ex:42: anonymous fn/2 in Phx2Ban.Metrics.init/1
                (elixir 1.15.8) lib/enum.ex:4356: Enum.map/2
                (phx_2_ban 0.2.0) lib/phx_2_ban/metrics.ex:38: Phx2Ban.Metrics.init/1
                (stdlib 4.3.1.5) gen_server.erl:851: :gen_server.init_it/2
                (stdlib 4.3.1.5) gen_server.erl:814: :gen_server.init_it/6
                (stdlib 4.3.1.5) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by jaeyson** [comment]
oh it has something to do with recent version of Elixir right? 1.17?

(UndefinedFunctionError) function DateTime.shift/2

**Comment by PJUllrich** [comment]
Oh yes it seems like it. Can you update your project to 1.17? 😬 Otherwise, we'd have to change quite a few calls to that function.

**Comment by PJUllrich** [comment]
Could you share that part of your GitHub action YAML file, please? And also the last command which deploys the application, please.

**Comment by jaeyson** [comment]
```yaml
name: continuous integration
on:
  workflow_call:
  pull_request:
  push:
jobs:
  ci_test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sample_test
        image: 'postgres:14-alpine'
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Elixir/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: 1.17.x
      - name: Cache deps and build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mixtest-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mixtest-
      - name: Add EZSuite Repo
        run: |
          mix hex.repo add ezsuite https://ezsuite.dev/repo \
          --auth-key ${{ secrets.EZSUITE_AUTH_KEY }} \
          --fetch-public-key SHA256:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
      - name: Install Dependencies
        run: |
          mix local.rebar --if-missing
          mix local.hex --if-missing
          mix deps.get
      - name: Check format and style guide
        run: |
          mix format --check-formatted
...
```

**Comment by jaeyson** [comment]
here's the error

```bash
Run mix hex.repo add ezsuite https://ezsuite.dev/repo \
  mix hex.repo add ezsuite https://ezsuite.dev/repo \
  --auth-key  \
  --fetch-public-key SHA256:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
  shell: /usr/bin/bash -e {0}
  env:
    MIX_ENV: test
    INSTALL_DIR_FOR_OTP: /home/runner/work/_temp/.setup-beam/otp
    INSTALL_DIR_FOR_ELIXIR: /home/runner/work/_temp/.setup-beam/elixir
  
** (Mix) Could not invoke task "hex.repo": 1 error found!
--auth-key : Missing argument of type string
Error: Process completed with exit code 1.
```

**Comment by PJUllrich** [comment]
Could you please double-check that you added the auth-key as `Repository Secret` to your GitHub Action secrets? And that its name is really `EZSUITE_AUTH_KEY` (I made the mistake myself that I named it `EZSUITE_API_KEY` instead :D)

**Comment by jaeyson** [comment]
Yes, I checked the name and it's `EZSUITE_AUTH_KEY` on your docs. I even re-added it in github action repo secret. Still I don't know why It didnt work. The above yaml file is CI, which is needed by my cd yaml file:

```yaml
name: Staging CD
on:
  push:
    branches:
      - staging
jobs:
  staging_ci_workflow:
    uses: ./.github/workflows/ci.yml
  staging_deploy:
    runs-on: ubuntu-latest
    needs: [staging_ci_workflow]
    concurrency:
      group: deploy-group    # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.STAGING_FLY_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --app sample-staging --config staging.toml --remote-only --http-failover --build-secret ezsuite_auth_key="${{ secrets.EZSUITE_AUTH_KEY }}"
```
<img width="807" alt="Screenshot 2024-11-28 at 23 06 24" src="https://github.com/user-attachments/assets/c35e2070-ea5e-4570-ac9f-8b5d31db1adc">

**Comment by jaeyson** [comment]
with logging enabled:

```bash
##[debug]Evaluating condition for step: 'Add EZSuite Repo'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Add EZSuite Repo
##[debug]Loading inputs
##[debug]Evaluating: format('mix hex.repo add ezsuite https://ezsuite.dev/repo \
##[debug]--auth-key {0} \
##[debug]--fetch-public-key SHA[2](https://github.com/org_name/repo/actions/runs/12071181993/job/33662747656#step:6:2)56:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
##[debug]', secrets.EZSUITE_AUTH_KEY)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'mix hex.repo add ezsuite https://ezsuite.dev/repo \
##[debug]--auth-key {0} \
##[debug]--fetch-public-key SHA256:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating secrets:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'EZSUITE_AUTH_KEY'
##[debug]..=> null
##[debug]=> 'mix hex.repo add ezsuite https://ezsuite.dev/repo \
##[debug]--auth-key  \
##[debug]--fetch-public-key SHA256:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
##[debug]'
##[debug]Result: 'mix hex.repo add ezsuite https://ezsuite.dev/repo \
##[debug]--auth-key  \
##[debug]--fetch-public-key SHA256:5WqcbEXE2PRHFpPrlJeaCCS1mAokfq6Bf/rdKzukVQ4
##[debug]'
##[debug]Loading env
Run mix hex.repo add ezsuite https://ezsuite.dev/repo \
##[debug]/usr/bin/bash -e /home/runner/work/_temp/022772eb-79[3](https://github.com/org_name/repo/actions/runs/12071181993/job/33662747656#step:6:3)e-4453-8849-0db10cc7fed5.sh
** (Mix) Could not invoke task "hex.repo": 1 error found!
--auth-key : Missing argument of type string
Error: Process completed with exit code 1.
##[debug]Finishing: Add EZSuite Repo
```

**Comment by PJUllrich** [comment]
Sorry but are you sure you've copy&pasted the auth key into the field section of the `EZSUITE_AUTH_KEY`? It seems the secret exists but is empty?

**Comment by jaeyson** [comment]
Yes I even re-added that value of that secret three times. I even force pushed the commit and deleted all caches in github actions. Will give you update some time if I found a workaround. Thanks for helping me out.

**Comment by jaeyson** [comment]
@PJUllrich I got the fix now based on this [reference](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow):

> Workflows that call reusable workflows in the same organization or enterprise can use the `inherit` keyword to implicitly pass the secrets.

```yaml
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
```

It's because I used a reusable workflow 🤦🏾. Here's what is added:

```yaml
name: Staging CD
on:
  push:
    branches:
      - staging
jobs:
  staging_ci_workflow:
    uses: ./.github/workflows/ci.yml
    secrets: inherit # <-- THIS PART!!!!
  staging_deploy:
    runs-on: ubuntu-latest
    needs: [staging_ci_workflow]
    concurrency:
      group: deploy-group    # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.STAGING_FLY_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --app sample-staging --config staging.toml --remote-only --http-failover --build-secret ezsuite_auth_key="${{ secrets.EZSUITE_AUTH_KEY }}"
```

After deployed to fly.io, I confirm that it worked (dashboard)
<img width="1075" alt="Screenshot 2024-11-28 at 23 51 36" src="https://github.com/user-attachments/assets/a367bbe9-299f-419b-89cc-234b8939875d">
